# This file was generated by GoReleaser. DO NOT EDIT.
cask "fortem" do
  version "0.3.1"

  on_macos do
    on_arm do
      sha256 "5ecfa4a09af389b30d5ba8d86e0f2ad7b9185329c573f62a496e79a43e594baa"
      url "https://github.com/cybrixcc/fortem-releases/releases/download/v#{version}/fortem_#{version}_macOS_arm64.tar.gz"
    end
    on_intel do
      sha256 "0d93b2eb8601cb10159417ce8826190e5d99eeec66ea5a3fbd8551a5cf6b012f"
      url "https://github.com/cybrixcc/fortem-releases/releases/download/v#{version}/fortem_#{version}_macOS_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a976146e1f802769b596baa1aad64356abcce22a3b963bddf354bb50382f66ed"
      url "https://github.com/cybrixcc/fortem-releases/releases/download/v#{version}/fortem_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "87ddab7a41a20782e637c337a30ca8c66bb1f57fad25195fc49a774d47fd4b09"
      url "https://github.com/cybrixcc/fortem-releases/releases/download/v#{version}/fortem_#{version}_linux_x86_64.tar.gz"
    end
  end

  name "fortem"
  desc "Local evidence-first Kubernetes incident workspace"
  homepage "https://fortem.dev/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fortem"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/fortem"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Fortem reads your existing kubeconfig and is read-only unless started
    explicitly with --manage. Release archives are not yet notarized.
  EOS
end
