# This file was generated by GoReleaser. DO NOT EDIT.
cask "fortem" do
  version "0.3.4"

  on_macos do
    on_arm do
      sha256 "b07c2e62c7baa635a907dba7563d67eaab7497771dfbda683da34e382a0ab4f1"
      url "https://github.com/cybrixcc/fortem-releases/releases/download/v#{version}/fortem_#{version}_macOS_arm64.tar.gz"
    end
    on_intel do
      sha256 "e071a12415593d7c3018f3bf623ce8299336cde4273ba23271b9b49a2efc71e9"
      url "https://github.com/cybrixcc/fortem-releases/releases/download/v#{version}/fortem_#{version}_macOS_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1ab10a59dc689704de432711b55381baaf88303af4eceb3e1138b8dfe9666419"
      url "https://github.com/cybrixcc/fortem-releases/releases/download/v#{version}/fortem_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2359d29e3d8f9248cb97c8eba40645f80a4a30bd8bbd5b7793668de00a58dd78"
      url "https://github.com/cybrixcc/fortem-releases/releases/download/v#{version}/fortem_#{version}_linux_x86_64.tar.gz"
    end
  end

  name "fortem"
  desc "Local evidence-first Kubernetes incident workspace"
  homepage "https://fortem.dev/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fortem"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fortem"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Fortem reads your existing kubeconfig and is read-only unless started
    explicitly with --manage. Release archives are not yet notarized.
  EOS
end
