# This file was generated by GoReleaser. DO NOT EDIT.
cask "fortem" do
  version "0.4.1"

  on_macos do
    on_arm do
      sha256 "e9beccc37250697056c95970dffd5000dacf0bd462980e49e90b434eb3bd71b6"
      url "https://github.com/cybrixcc/fortem-releases/releases/download/v#{version}/fortem_#{version}_macOS_arm64.tar.gz"
    end
    on_intel do
      sha256 "9f643866b6fcb573e4140222a914262681fbd35892f978ac1b68ddad98401353"
      url "https://github.com/cybrixcc/fortem-releases/releases/download/v#{version}/fortem_#{version}_macOS_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0b33b89c8a29bd81153459689f85493eed4384dcbb8669173bc75f10d25ff9dc"
      url "https://github.com/cybrixcc/fortem-releases/releases/download/v#{version}/fortem_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a5a57361ce129b712ec8b7d4c0349ff7578c08ce5f5f8f6a44615980b837c1b4"
      url "https://github.com/cybrixcc/fortem-releases/releases/download/v#{version}/fortem_#{version}_linux_x86_64.tar.gz"
    end
  end

  name "fortem"
  desc "Local evidence-first Kubernetes incident workspace"
  homepage "https://fortem.dev/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fortem"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/fortem"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Fortem reads your existing kubeconfig and is read-only unless started
    explicitly with --manage. Release archives are not yet notarized.
  EOS
end
