# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fortem < Formula
  desc "Local Kubernetes environment inspector"
  homepage "https://fortem.dev"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cybrixcc/fortem-releases/releases/download/v0.1.0/fortem_0.1.0_macOS_x86_64.tar.gz"
      sha256 "9d4f2d08121743199a4d911bdd70f10955b5f3bf3309509608d7a9cf23581be0"

      define_method(:install) do
        bin.install "fortem"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cybrixcc/fortem-releases/releases/download/v0.1.0/fortem_0.1.0_macOS_arm64.tar.gz"
      sha256 "e6172909c728bf76a17d40e7b3e00e64bac9f461ede1590cf04767971705824b"

      define_method(:install) do
        bin.install "fortem"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cybrixcc/fortem-releases/releases/download/v0.1.0/fortem_0.1.0_linux_x86_64.tar.gz"
      sha256 "ca5befbee84ec7db57465ad5bd74fdd03128740f1bc11d3e0d4c9087e6e068ce"
      define_method(:install) do
        bin.install "fortem"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cybrixcc/fortem-releases/releases/download/v0.1.0/fortem_0.1.0_linux_arm64.tar.gz"
      sha256 "d24c400586bdc3d63c71de1f2d56d5cbbbdd4aa7941b565910bd9cbab9340bcf"
      define_method(:install) do
        bin.install "fortem"
      end
    end
  end

  def caveats
    <<~EOS
      Fortem reads your existing kubeconfig and is read-only unless started
      explicitly with --manage.
    EOS
  end
end
